### ISSUE TITLE
Swiper with RequireJS (TypeError: f.wrapper.transition is not a function)

### ISSUE THREAD

**Issue by Desvelo1** [nolimits4web/Swiper#1246]
Hi, 

When I use Swiper with RequireJS sometimes I get such error:

```
TypeError: f.wrapper.transition is not a function
...)},f.setWrapperTransition=function(e,a){f.wrapper.transition(e),"slide"!==f.para...
	
swiper.....min.js (line 15, row 29993)
```

Is it possible to use Swiper with RequireJS? 

Thanks in advance!

**Comment by nolimits4web** [comment]
You get this error "sometimes" or always?

**Comment by Desvelo1** [comment]
About Every 3rd refresh i get this retor - sometines few times in row.

W dniu środa, 22 kwietnia 2015 Vladimir Kharlampidi <
notifications@github.com> napisał(a):

> You get this error "sometimes" or always?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolimits4web/Swiper/issues/1246#issuecomment-95247457>
> .
>


-- 
Pozdrawiam serdecznie,
Piotr Osmoła

**Comment by silentrain** [comment]
I have used swiper in angularjs successfully.we need to use directive to init swiper when slide has been inited.

**Comment by Desvelo1** [comment]
@silentrain thanks for you answer - did you have the same problem? Could you describe it a little bit more?

**Comment by owldesign** [comment]
Im getting similar error when I updated to swiper 3 from 2.
`h.wrapper.transition is not a function`

**Comment by nolimits4web** [comment]
@owldesign are you using vanilla or jQuery version?

**Comment by owldesign** [comment]
This happened on the jquery one.

**Comment by luchun** [comment]
h.wrapper.transition is not a function ,I get this  when use require.js

**Comment by WeBaGeMyghty** [comment]
Same problem here, any solution yet?

**Comment by AmiWeb-ru** [comment]
same problem with Drupal. But no RequireJS used. Drupal 7.38 + JQuery Update + some modules — «h.wrapper.transition is not a function» error

**Comment by nolimits4web** [comment]
Should be fixed in 3.1.0 with `swiper.jquery.umd.js`

**Comment by barlas** [comment]
i got this error and solved this with using native javascript swiper, not jquery swiper

**Comment by danielemesh** [comment]
Also got the error, out of the blue today (weird!). Never happened on my website, I am using the jquery version (3.2.0), switched to the vanilla js version (3.3.1) and it all works fine.

**Comment by christianhaller** [comment]
same here

**Comment by Villanuevand** [comment]
Same here...

**Comment by lixiaodong** [comment]
@nolimits4web I got the same error ,when i use swiper in requirejs.
   require(['jquery','underscore','swiper'],function($,_,Swiper) {



        var mySwiper = new Swiper ('.swiper-container', {
            // direction: 'vertical',
            loop: true,

            // 如果需要分页器
            pagination: '.swiper-pagination'

        });

**Comment by lixiaodong** [comment]
# It's fixed!!!!
this error has confused me 2 days.now it's fixed!
this issue fixed  in 3.1.0 with swiper.jquery.umd.js.@nolimits4web you are right.
**when i use swiper.jquery.umd.js ,everything runs well.**
thank you for your comment @nolimits4web ,but i give you -1.
because your comment is not very clear ...

**Comment by shukriadams** [comment]
Well, this just saved me from an early, stress-related death.

**Comment by wolfierine** [comment]
It also works well if you use any version with js.
