### ISSUE TITLE
`Cannot convert undefined or null to object` when using `Thumbs` module

### ISSUE THREAD

**Issue by bnn1** [nolimits4web/swiper#5630]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/bnn1/swiper-issue

### Bug description

When creating component from [example](https://swiperjs.com/react#thumbs) in React app, app throws runtime error `TypeError: Cannot convert undefined or null to object`. 

Reproduction link contains next.js app but it is possible to reproduce with pure react bootstrapped with CRA

**Steps to reproduce:**
1. Create react app `yarn create react-app`
2. Install `swiper`
3. Create component `Carousel` and add the following code
<details>
<summary>code</summary>

```js
import React, { useState } from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import { Thumbs } from "swiper";
import "swiper/css";

export const Component = () => {
  // store thumbs swiper instance
  const [thumbsSwiper, setThumbsSwiper] = useState(null);

  return (
    <main>
      {/* Main Swiper -> pass thumbs swiper instance */}
      <h1>hello</h1>
      <Swiper modules={[Thumbs]} thumbs={{ swiper: thumbsSwiper || null }}>
        <SwiperSlide>1</SwiperSlide>
        <SwiperSlide>2</SwiperSlide>
        <SwiperSlide>3</SwiperSlide>
        <SwiperSlide>4</SwiperSlide>
        <SwiperSlide>5</SwiperSlide>
      </Swiper>

      {/* Thumbs Swiper -> store swiper instance */}
      {/* It is also required to set watchSlidesProgress prop */}
      <Swiper modules={[Thumbs]} watchSlidesProgress onSwiper={setThumbsSwiper}>
        {/* ... */}        <SwiperSlide>1</SwiperSlide>
        <SwiperSlide>2</SwiperSlide>
        <SwiperSlide>3</SwiperSlide>
        <SwiperSlide>4</SwiperSlide>
        <SwiperSlide>5</SwiperSlide>

      </Swiper>
    </main>
  );
};

```
</details>
4. Use `Component` inside `App.js` file

```js
import { Component } from './Component';

function App() {
  return (
    <div className="App">
      <Component />
    </div>
  );
}

export default App;
```
5. Run application `yarn start`
6. Navigate to `localhost:3000`
7. Open dev tools

### Expected Behavior

No errors occur during runtime

### Actual Behavior

Errors occur during runtime

### Swiper version

8.1.0

### Platform/Target and Browser Versions

Linux (arch), Chrome Version 100.0.4896.88 (Official Build) (64-bit)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by linkb15** [comment]
I am facing with this issue as well with Nextjs 12 + React 18

**Comment by enkhee** [comment]
+1

**Comment by zahra-tavakkoli** [comment]
I have same issue with 
react 17.0.2
swiper 8.1.3
webpack 5.70.0

**Comment by MaksimAmelchenko** [comment]
the workaround is 
`thumbs={{ swiper: thumbsSwiper }}` 
replace to
`thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`

**Comment by muhaymin-bin-mehmood** [comment]
> 

Will you please tell how can I fix it. I had almost the same scenario 

<Swiper
                                                        onSwiper={setThumbsSwiper}
                                                        spaceBetween={10}
                                                        slidesPerView={2}
                                                        watchSlidesProgress
                                                        dir={!langDirection ? "rtl" : "ltr"}
                                                        key={langDirection}
                                                        // loop={true}
                                                        freeMode={true}
                                                        modules={[FreeMode, Navigation, Thumbs]}
                                                        className={`mySwiper3 ${carListing.media.length > 1 && carListing.media.length < 3 ? 'thumbSlideTwo' : ''}`}
                                                        breakpoints={{
                                                            360: {
                                                                slidesPerView: carListing.media.length > 2 ? 2 : carListing.media.length <= 0 ? 2 : carListing.media.length,
                                                                spaceBetween: 10
                                                            },
                                                            380: {
                                                                slidesPerView: carListing.media.length > 2 ? 3 : carListing.media.length <= 0 ? 3 : carListing.media.length,
                                                                spaceBetween: 10
                                                            },
                                                            460: {
                                                                slidesPerView: carListing.media.length > 3 ? 3 : carListing.media.length <= 0 ? 3 : carListing.media.length,
                                                                spaceBetween: 5
                                                            },
                                                            700: {
                                                                slidesPerView: carListing.media.length > 4 ? 4 : carListing.media.length <= 0 ? 4 : carListing.media.length,
                                                                spaceBetween: 0
                                                            },
                                                            900: {
                                                                slidesPerView: carListing.media.length > 3 ? 3 : carListing.media.length <= 0 ? 3 : carListing.media.length,
                                                                spaceBetween: 15
                                                            },
                                                            1200: {
                                                                slidesPerView: carListing.media.length > 4 ? 4 : carListing.media.length <= 0 ? 4 : carListing.media.length,
                                                            },
                                                        }}
                                                    >

**Comment by Hyachin** [comment]
> 

thanks a lot. It works well. But do you know how can I change the top-picture where I hover the bottom-thumbnail?

**Comment by Hyachin** [comment]
> the workaround is `thumbs={{ swiper: thumbsSwiper }}` replace to `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`

thanks a lot. It works well. But do you know how can I change the top-picture where I hover the bottom-thumbnail?

**Comment by Hyachin** [comment]
> the workaround is `thumbs={{ swiper: thumbsSwiper }}` replace to `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`

thanks a lot. It works well. But do you know how can I change the top-picture when I hover the bottom-thumbnail?

**Comment by Stusaw** [comment]
Seems like this call is incorrect? Should be Swiper.default.defaults

`    extend(params, Swiper.defaults);`
```
function extend(target, src) {
    const noExtend = ['__proto__', 'constructor', 'prototype'];
    Object.keys(src) // Src is undefined
        .filter((key) => noExtend.indexOf(key) < 0)
        .forEach((key) => {
        if (typeof target[key] === 'undefined') {
            target[key] = src[key];
            return;
        }
        if (target[key] && !src[key]) {
            return;
        }
        if (isObject(src[key]) && isObject(target[key]) && Object.keys(src[key]).length > 0) {
            if (src[key].__swiper__)
                target[key] = src[key];
            else
                extend(target[key], src[key]);
        }
        else {
            target[key] = src[key];
        }
    });
}
```

**Comment by jason-work-git** [comment]
> Why is the discussion closed? Tre error is actual #5801

the answer of the [MaksimAmelchenko](https://github.com/MaksimAmelchenko) is working

**Comment by Rustambek-Mamadaliyev0301** [comment]
> vaqtinchalik yechim bilan `thumbs={{ swiper: thumbsSwiper }}` almashtiriladi `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`

buni

> vaqtinchalik yechim bilan `thumbs={{ swiper: thumbsSwiper }}` almashtiriladi `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`

where do we write this?

**Comment by muhaymin-bin-mehmood** [comment]
> > vaqtinchalik yechim bilan `thumbs={{ swiper: thumbsSwiper }}` almashtiriladi `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`
> 
> buni
> 
> > vaqtinchalik yechim bilan `thumbs={{ swiper: thumbsSwiper }}` almashtiriladi `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`
> 
> where do we write this?

Did you figured out ?

**Comment by cansariyar** [comment]
> the workaround is `thumbs={{ swiper: thumbsSwiper }}` replace to `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`

I had the same problem, your solution worked thank you very much.

**Comment by xmmwc** [comment]
> 

same problem. src is undefined. use import {Swiper} from 'swiper/vue'.
maybe something wrong with build not using esm import

**Comment by javadgt** [comment]
thumbs={{swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null}}

**Comment by MdWahiduzzamanEmon** [comment]
<Swiper
        cssMode={true}
        loop={true}
        spaceBetween={10}
        navigation={true}
        thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}
        onInit={(swiper) => {
          setInit(swiper);
        }}
        modules={[FreeMode, Navigation, Thumbs]}
        className="mySwiper2"
      />
      
      
      
`thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}
`

**Comment by RodrigoTomeES** [comment]
The error persist in React 18.2, NextJS 12.3.1 and Swiper 10.1.0. But can be fixed with the workaround of @MaksimAmelchenko.

This information should be added to the documentation: https://swiperjs.com/react#thumbs. I tried to contribute with it but I didn't found the source code.

**Comment by dingolandia** [comment]
One more step is needed to work with React 18.2.0. You must set the type of your state as 'SwiperClass.'
const [thumbsSwiper, setThumbsSwiper] = useState<SwiperClass>();

**Comment by alex-lenk** [comment]
> TS2339: Property  destroyed  does not exist on type  never 

Swiper 11.05

`
import React, { useState } from 'react';
import { Swiper as SwiperType } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import { FreeMode, Navigation, Thumbs } from 'swiper/modules';

const ProductCarousel: React.FC = () => {
  const [thumbsSwiper, setThumbsSwiper] = useState<SwiperType | null>(null);

  return (
    <div>
      <Swiper
        spaceBetween={ 10 }
        navigation={ true }
        thumbs={ { swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null } }
        modules={ [FreeMode, Navigation, Thumbs] }
      >
        { detailCarouselsMain.map((instance, index) => (
          <SwiperSlide key={ instance.img + index }>
            <S.ProductCarouselImg src={ instance.img } alt={ 'alt' } />
          </SwiperSlide>
        )) }
      </Swiper>

      <Swiper
        onSwiper={ setThumbsSwiper }
        spaceBetween={ 10 }
        slidesPerView={ 4 }
        freeMode={ true }
        watchSlidesProgress={ true }
        modules={ [FreeMode, Navigation, Thumbs] }
      >
        { detailCarouselsMain.map((instance, index) => (
          <SwiperSlide key={ instance.img + index }>
            <S.ProductCarouselImg src={ instance.img } alt={ 'alt' } />
          </SwiperSlide>
        )) }
      </Swiper>
    </div>
  );
};

export default Carousel;
`

**Comment by alex-lenk** [comment]
> TS2339: Property  destroyed  does not exist on type  never

**Swiper 11.05**

```
import React, { useState } from 'react';
import { Swiper as SwiperType } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import { FreeMode, Navigation, Thumbs } from 'swiper/modules';
import * as S from './styles';
import detailMain2 from 'assets/img/example/detail/detail-main-2.png';
import detailMain3 from 'assets/img/example/detail/detail-main-3.png';
import detailMain4 from 'assets/img/example/detail/detail-main-4.png';
import detailMain5 from 'assets/img/example/detail/detail-main-5.jpg';

interface ImageItem {
  img: string;
}

const detailCarouselsMain: ImageItem[] = [
  { img: detailMain2 },
  { img: detailMain3 },
  { img: detailMain5 },
  { img: detailMain4 },
  { img: detailMain5 },
];

const ProductCarousel: React.FC = () => {
  const [thumbsSwiper, setThumbsSwiper] = useState<SwiperType | null>(null);

  console.log('thumbsSwiper', thumbsSwiper);

  return (
    <S.ProductCarousel>
      <Swiper
        spaceBetween={ 10 }
        navigation={ true }
        thumbs={ { swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null } }
        modules={ [FreeMode, Navigation, Thumbs] }
      >
        { detailCarouselsMain.map((instance, index) => (
          <SwiperSlide key={ instance.img + index }>
            <S.ProductCarouselImg src={ instance.img } alt={ 'alt' } />
          </SwiperSlide>
        )) }
      </Swiper>

      <Swiper
        onSwiper={ setThumbsSwiper }
        spaceBetween={ 10 }
        slidesPerView={ 4 }
        freeMode={ true }
        watchSlidesProgress={ true }
        modules={ [FreeMode, Navigation, Thumbs] }
      >
        { detailCarouselsMain.map((instance, index) => (
          <SwiperSlide key={ instance.img + index }>
            <S.ProductCarouselImg src={ instance.img } alt={ 'alt' } />
          </SwiperSlide>
        )) }
      </Swiper>
    </S.ProductCarousel>
  );
};

export default ProductCarousel;

```

**Comment by Crazy0717** [comment]
> the workaround is `thumbs={{ swiper: thumbsSwiper }}` replace to `thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}`

thank you

**Comment by imranhwebdev** [comment]
thumbs={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }}

**Comment by rost21** [comment]
thumbs={{ swiper: thumbsSwiper?.destroyed ? null : thumbsSwiper }}

**Comment by alicerocheman** [comment]
This shouldn't be closed.
The workaround doesn't always work, it doesn't work in my case, I still get the error after applying the workaround.
