### ISSUE TITLE
The space between slides increases when resize the window and does not keep the same space between them

### ISSUE THREAD

**Issue by slim-hmidi** [nolimits4web/swiper#6825]
### Check that this is really a bug

- [ ] I confirm

### Reproduction link

https://codesandbox.io/s/upbeat-resonance-clyzx9?file=/index.tsx&resolutionWidth=560&resolutionHeight=675

### Bug description

I have a list of cards that should be displayed correctly in different devices sizes.
When I resize the window in mobile devices the space between slides should be always 24px but it's not the case. The space between increase when I start increase the the device width.

### Expected Behavior

The space between should be the same according the breakpoints configuration set in the Swiper component.

### Actual Behavior

The Space between slides increases accordingly and does not respect the configuration I have set.

### Swiper version

9.1.1

### Platform/Target and Browser Versions

macOS Ventura 13.4.1 (22F82)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
Would be good to see the demo using pure swiper, otherwise i suspect styles conflict with other lib and Swiper 10 must be used

**Comment by Mansurkhoja** [comment]
> Would be good to see the demo using pure swiper, otherwise i suspect styles conflict with other lib and Swiper 10 must be used

swiper 9.4.1 v work in ios 15.7.7 but swiper 10.0.3 not. why?

**Comment by slim-hmidi** [comment]
@nolimits4web upgrading swiper to v10.0.3 does not work and throws this error:
```
TypeError: mod is not a function

```

**Comment by slim-hmidi** [comment]
@nolimits4web the reproduction is [here](https://codesandbox.io/p/sandbox/swiper-react-navigation-forked-lwhtfs?file=%2Fsrc%2FCard.jsx%3A20%2C30) if you want to check it.

**Comment by nolimits4web** [comment]
I see everything works correctly, use code inspector to see what is wrong with your styles
