### ISSUE TITLE
Bug after upgrading to 8.0.4 with Swiper Events

### ISSUE THREAD

**Issue by Sergiobop** [nolimits4web/swiper#5454]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

none

### Bug description

Error: node_modules/swiper/angular/angular/src/swiper-events.d.ts:3:50 - error TS2344: Type 'SwiperEvents[Property]' does not satisfy the constraint '(...args: any) => any'.
  Type '((swiper: Swiper) => void) | ((swiper: Swiper) => void) | ((swiper: Swiper) => void) | ((swiper: Swiper) => void) | ((swiper: Swiper) => void) | ((swiper: Swiper) => void) | ... 75 more ... | undefined' is not assignable to type '(...args: any) => any'.
    Type 'undefined' is not assignable to type '(...args: any) => any'.

3     [Property in keyof SwiperEvents]: Parameters<SwiperEvents[Property]>;
                                                   ~~~~~~~~~~~~~~~~~~~~~~

### Expected Behavior

The project should compile as usual

### Actual Behavior

The compilation throws an error 

### Swiper version

8.0.4

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
https://swiperjs.com/migration-guide-v8

**Comment by Sergiobop** [comment]
I saw the migration guide @nolimits4web, but i'm not using any events right now, so i can't update anything related to the point stated in the guide

**Comment by BernhardBehrendt** [comment]
Have the same issue after upgrading from **8.03** (works perfect) to **8.0.5** where this error occurs.

**Comment by nolimits4web** [comment]
cc @vltansky

**Comment by vltansky** [comment]
released in `v8.0.6`
