### ISSUE TITLE
Namespace 'React' has no exported member 'VoidFunctionComponent'

### ISSUE THREAD

**Issue by shlcharolia** [nolimits4web/swiper#5763]
Hi team,

I am working on "react": "16.11.0" with typescript and using  "swiper": "^8.2.2". I got  the following error while creating a build package.

```
**node_modules/swiper/react/swiper-react.d.ts:473:34 - error TS2694: Namespace 'React' has no exported member 'VoidFunctionComponent'.

473 declare const SwiperSlide: React.VoidFunctionComponent<SwiperSlideProps>;  
                                     ~~~~~~~~~~~~~~~~~~~~~
Found 1 error.**
```

I have also look into the swiper github repo and find that the package contain a wrong type name "VoidFunctionComponent" instead it will be "FunctionComponent".

Kindly fix this in you repo and also provide the solution for the above issue.

Thanks

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Swiper, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
