### ISSUE TITLE
Swiper 6.4.0 typings errors

### ISSUE THREAD

**Issue by ettoredn** [nolimits4web/swiper#4025]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.0

### What you did
I updated to 6.4.0

### Expected Behavior
No typescript compilation error.

### Actual Behavior
```
node_modules/swiper/types/swiper-class.d.ts:372:17 - error TS7006: Parameter 'breakpoints' implicitly has an 'any' type.

372   getBreakpoint(breakpoints): string;
                    ~~~~~~~~~~~
Found 1 error.
```

**Comment by ettoredn** [comment]
Introduced in https://github.com/nolimits4web/swiper/commit/5be5c78f8bd1cf151d50f24fadd68134015174a9#diff-4b3913ecd4a38723e9650f7d5a987e7011b9038210eb38373a080abacb1e3dd3
